spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    password: 123456
    url: jdbc:mysql://localhost:3306/web1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
